export default class CommonConstants {
  /**
   * 组件尺寸
   */
  static readonly FULL_WIDTH = '100%';
  static readonly FULL_HEIGHT = '100%';

  static readonly HALF_SIZE = '50%';
  static readonly CONTENT_SIZE = '95%';
  static readonly FONT_BOLDER = '700';
  /**
   * Input length of the account.
   */
  static readonly INPUT_ACCOUNT_LENGTH = 11;

  /**
   *  Input length of the password.
   */
  static readonly INPUT_PASSWORD_LENGTH = 8;

  /**
   *  Left padding of the input box
   */
  static readonly INPUT_PADDING_LEFT = 0;

  /**
   * Delay time of simulated login
   */
  static readonly LOGIN_DELAY_TIME = 2000;

  /**
   * Common Spacing of Components
   */
  static readonly COMMON_SPACE = 12;

  /**
   * Title text of the home page
   */
  static readonly HOME_TITLE = '首页';

  /**
   * Title text of the classify page
   */
  static readonly CLASSIFY_TITLE = '分类';

  /**
   * Title text of the setting page
   */
  static readonly MINE_TITLE = '我的';

  /**
   * Spacing of other login methods
   */
  static readonly LOGIN_METHODS_SPACE = 44;

  /**
   * The width or height of the component is spread across the parent component.
   */
  static readonly FULL_PARENT = '100%';

  /**
   * The width of button
   */
  static readonly BUTTON_WIDTH = '90%';

  /**
   * Home tab index
   */
  static readonly HOME_TAB_INDEX = 0;

  /**
   * Classify tab index
   */
  static readonly CLASSIFY_TAB_INDEX = 1;

  /**
   * Mine tab index
   */
  static readonly MINE_TAB_INDEX = 2;

  /**
   * label font weight 400.
   */
  static readonly LABEL_FONT_WEIGHT: number = 400;

  /**
   * title font weight 500.
   */
  static readonly TITLE_FONT_WEIGHT: number = 500;

  /**
   * course item padding 12.
   */
  static readonly COURSE_ITEM_PADDING: number = 12;

  /**
   * loading duration 2000.
   */
  static readonly LOADING_DURATION: number = 2000;

  /**
   * title line number 2.
   */
  static readonly TITLE_LINE_NUMBER: number = 2;

  /**
   * 100 percent.
   */
  static readonly FULL_PERCENT: string = '100%';

  /**
   * classify title percent.
   */
  static readonly CLASSIFY_TITLE_PERCENT: string = '55%';
}
